import '@styles/globals.css';

import { Roboto } from 'next/font/google'

import Nav from '@components/Nav'

import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import Menu from '@components/Menu';
const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
})
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    // overflor: 'hidden'
}

export default function RootLayout({ children }) {
    return <html lang="en">
        <link rel="icon" href="https://deo.shopeemobile.com/shopee/shopee-seller-live-sg/mmf_portal_seller_root_dir/shopee/favicon.ico" />
        <body className={`${roboto.className} flex flex-row overflow-hidden h-screen`}>
            <Menu />
            <main className="w-full h-screen flex flex-col">
                {children}
            </main>
            <ToastContainer autoClose={3000} />
        </body>
    </html>;
}
