import Nav from '@components/Nav'
import { Inter } from 'next/font/google'
import '@styles/globals.css';
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    overflor: 'hidden'
}

export default function RootLayout({ children }) {
    return <html lang="en">
        <link  rel="icon" href="https://deo.shopeemobile.com/shopee/shopee-seller-live-sg/mmf_portal_seller_root_dir/shopee/favicon.ico" />
        <body className={inter.className}>
            <Nav />
            {children}
            <ToastContainer />
        </body>
    </html>;
}
